name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          repositories: 200
          repositories_affiliations: owner, collaborator
          

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3

      # name: Comment reactions
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_limit_discussions: 1000
          plugin_reactions_limit_discussions_comments: 1000
          plugin_reactions_details: percentage

      # name: achievements
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, deployer, maintainer, developer
          plugin_achievements_threshold: X

      # name: Compact display
      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.achievements.compact.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_achievements: yes
      #     plugin_achievements_only: >-
      #       polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
      #       scripter, packager, explorer, infographile, manager
      #     plugin_achievements_display: compact
      #     plugin_achievements_threshold: X
          
      # name: Most used (with details)
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            VHDL, Verilog
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_days: 0
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
  
      # # name: Repositories and diff history
      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.lines.history.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_lines: yes
      #     plugin_lines_delay: 30
      #     plugin_lines_sections: base
      #     plugin_lines_repositories_limit: 10
      #     plugin_lines_history_limit: 0

      # name: python snippet of the day
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: python
          plugin_code_load: 1000
          plugin_code_lines: 12
          plugin_code_days: 0
        
      # name: GitHub Discussions
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_categories_limit: 0

      # name: Notable contributions Indepth analysis
      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.notable.indepth.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_notable: yes
      #     plugin_notable_indepth: no
      #     plugin_notable_repositories: yes
      #     plugin_notable_types: pull_request, issue
      #     plugin_notable_from: organization

      # name: Recent activity
      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.activity.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_activity: yes
      #     plugin_activity_limit: 5
      #     plugin_activity_days: 0
      #     plugin_activity_visibility: public 
      #     plugin_activity_filter: pr, release, review
